# -*- coding: utf-8 -*-
"""LinearAlgebraHomework3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14SV8kVi-R1FLntKCguofL64CV9tyd3wl
"""

import numpy as np
import matplotlib.pyplot as plt

def characteristic_polynomial(A, t):
    return np.linalg.det(A - t * np.eye(3))

def plot_characteristic_polynomial(A, a_value):
    t = np.linspace(0, 3, 300)
    p = [characteristic_polynomial(A, ti) for ti in t]
    plt.plot(t, p, label=f'a = {a_value}')
    plt.ylim(-10, 10)


a_matrix = [32, 31.9, 31.8, 32.1, 32.2]

plt.figure(figsize=(12, 8))

for a in a_matrix:
    A = np.array([
        [-6, 28, 21],
        [4, -15, -12],
        [-8, a, 25]
    ])

    # Compute eigenvalues
    eigenvalues = np.linalg.eigvals(A)
    print(f"For a = {a}, eigenvalues are: {eigenvalues}")

    # Plot characteristic polynomial
    plot_characteristic_polynomial(A, a)

plt.xlabel('t')
plt.ylabel('p(t)')
plt.title('Characteristic Polynomials for the Values of a')
plt.legend()
plt.grid(True)
plt.show()

# Describe changes in eigenvalues
print("\nDescription of how the graphs reveal changes in eigenvalues:")
print("1. The x-intercepts of each graph represent the eigenvalues.")
print("2. As 'a' changes, we can observe shifts in these x-intercepts.")
print("3. The number of x-intercepts indicates the number of real eigenvalues.")
print("4. Sudden changes in the shape of the graph may indicate a transition")
print("   between real and complex eigenvalues.")
print("5. The value of 'a' that causes the most significant changes in the graph")
print("   is likely a critical value where the nature of eigenvalues changes.")

